name: Update CSV

on:
  push:
    paths:
      - concerts.csv

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add concerts.csv
          git commit -m "Update concerts.csv with new entries"
          git push
